// Every user-facing string in Daybook. Components import from here; nothing
// user-facing is a literal in a component (CLAUDE.md protocol 5).
// Voice: plain, warm, British. Sentence case. No exclamation marks, no emoji.
// src/copy.test.ts checks every string in this file.

export const copy = {
  app: {
    name: "Daybook",
    description: "A logbook for the practical side of therapy.",
  },
  // Sign in: boards SignIn and SignInCode. Headings, labels and buttons are
  // the canvas's words; the status lines fill states the canvas doesn't draw.
  signIn: {
    title: "Sign in",
    intro: "We'll email you a 6-digit code. No password to remember.",
    emailLabel: "Email",
    send: "Email me a code",
    sendNeedsEmail: "Enter your email to get a code",
    sending: "Sending a code",
    codeTitle: "Check your email",
    codeIntro: (email: string) => `We sent a code to ${email}. It works for 10 minutes.`,
    codeLabel: "6-digit code",
    verify: "Sign in",
    verifyNeedsCode: "Enter the 6-digit code",
    verifying: "Signing in",
    resend: "Send a new code",
    resent: "A new code is on its way.",
    differentEmail: "Use a different email",
    wrongCode: "That code didn't work. Check it against the latest email, or send a new one.",
    offline: "Signing in needs a connection. Try again when you're back online.",
    sendFailed: "The code couldn't be sent just now. Wait a minute, then try again.",
    privacy: "Your entries are yours. Nothing is shared unless you choose to.",
  },
  // Install prompt: boards Install (iOS) and InstallAndroid, canvas words.
  install: {
    title: "Put Daybook on your home screen",
    intro:
      "Reminders only work once it's there. It takes about ten seconds, and it opens like any other app.",
    iosStep1Before: "Tap the Share button",
    iosStep1After: "at the bottom of Safari.",
    shareLabel: "Share",
    iosStep2Before: "Scroll down and tap",
    iosStep2Strong: "Add to Home Screen",
    iosStep2After: ".",
    iosStep3Before: "Tap",
    iosStep3Strong: "Add",
    iosStep3After: ", then open Daybook from your home screen and sign in once more.",
    shareHint: "Share is down here",
    androidCardTitle: "What you get",
    androidCardBody:
      "Reminders at the times you choose. Logging works with no signal and syncs later. No browser bars.",
    androidFallbackBefore: "If the button doesn't do anything, tap",
    androidFallbackMenu: "⋮",
    androidFallbackMiddle: "in Chrome, then",
    androidFallbackStrong: "Add to Home screen",
    androidFallbackAfter: ".",
    androidInstall: "Install Daybook",
    notNow: "Not now",
  },
  // New / edit session: boards SessionEdit and SessionEditPast (10b), plus
  // the states the canvas doesn't draw (loading offline, saving, not found).
  sessionEdit: {
    newTitle: "New session",
    editTitle: "Edit session",
    close: "Close without saving",
    when: "When",
    hintDefault: (weekday: string) =>
      `Set to the next ${weekday} at your last session's time. Change it if yours is different.`,
    hintFirst: "Pick the date and time of your next appointment.",
    notesLabel: "Session notes",
    notesPlaceholder: "Anything worth keeping from the session",
    assignedHeading: "Assigned in session",
    assignedNoteLabel: "Anything else, not a practice yet",
    assignedNotePlaceholder: "e.g. notice when I check my phone to avoid talking",
    save: "Save session",
    saveNeedsWhen: "Pick a date and time to save",
    saving: "Saving",
    offline: "Saving needs a connection. Your changes are still here.",
    failed: "That didn't save. Your changes are still here, so try again in a minute.",
    loadOffline: "Opening this session needs a connection.",
    notFound: "That session isn't here any more.",
    backToSessions: "Back to sessions",
  },
  // Session detail: boards SessionDetail and SessionDetailPast (0b parts).
  sessionDetail: {
    back: "Sessions",
    edit: "Edit",
    today: "Today",
    upcoming: "Upcoming",
    done: "Done",
    notMarkedDone: "Not marked done",
    notes: "Session notes",
    noNotes: "No notes yet. Add them with Edit.",
    assigned: "Assigned in session",
    markDone: "Mark session as done",
    marking: "Marking it done",
    markNote: "The entries stay in your history.",
    markOffline: "Marking it done needs a connection. Nothing has changed.",
    markFailed: "That didn't go through, so nothing has changed. Try again in a minute.",
  },
  // Shared field words (DateTimeField, TextArea).
  fields: {
    date: "Date",
    time: "Time",
    pickDate: "Pick a date",
    pickTime: "Pick a time",
    dateChange: (value: string) => `Date, ${value}. Change`,
    timeChange: (value: string) => `Time, ${value}. Change`,
    optional: "(optional)",
  },
  // Placeholder screens for the tabs whose content arrives in later phases.
  // Each is replaced when its phase builds the real screen.
  today: {
    title: "Today",
    emptyTitle: "Nothing to log yet",
    emptyBody: "Once a practice is set up, what's on for today shows here.",
  },
  practices: {
    title: "Practices",
    emptyTitle: "No practices yet",
    emptyBody: "Practices from your sessions will be listed here.",
  },
  // Sessions list: boards Sessions and SessionsEmpty (canvas words), plus the
  // states the canvas doesn't draw (later sessions, loading offline).
  sessions: {
    title: "Sessions",
    emptyTitle: "No sessions yet",
    emptyBody: "Add your next appointment. Anything you flag will collect for it.",
    addFirst: "Add your next session",
    add: "Add a session",
    next: "Next session",
    today: "Today",
    tomorrow: "Tomorrow",
    days: "days",
    nextLabel: (date: string, time: string, when: string) =>
      `Next session, ${date} at ${time}, ${when}`,
    inDays: (n: number) => `in ${n} days`,
    later: "Later",
    past: "Past",
    noNotes: "No notes",
    markedDone: "Marked done",
    notMarkedDone: "Not marked done",
    rowMeta: (time: string, status: string) => `${time} · ${status}`,
    offline:
      "Sessions need a connection to load. Anything you add on the edit screen needs one too.",
    failed: "Sessions didn't load just now. Try again in a minute.",
  },
  history: {
    title: "History",
    emptyTitle: "Nothing logged yet",
    emptyBody: "Everything you log is kept here, newest first.",
  },
  // Settings: boards Settings, SettingsDelete1, SettingsDelete2. Canvas words,
  // plus the states it doesn't draw (busy, offline, not installed).
  settings: {
    title: "Settings",
    installRow: "Add to home screen",
    installed: "Installed on this phone",
    notInstalled: "Not on this phone yet",
    dataHeading: "Your data",
    exportRow: "Export my data",
    exportMeta: "Everything, as a JSON file. PDF comes later.",
    exporting: "Getting everything together",
    exportDone: "Exported. Check your downloads or Files.",
    exportOffline: "Exporting needs a connection. Try again when you're back online.",
    exportFailed: "The export didn't come through. Try again in a minute.",
    deleteRow: "Delete everything",
    deleteMeta: "From this phone and the server. Two steps.",
    about: "About Daybook",
    version: (v: string) => `Version ${v}`,
    signOut: "Sign out",
    footer: "Daybook is a logbook, not a coach and not emergency support.",
    delete: {
      step1Label: "Step 1 of 2",
      step1Title: "Delete everything?",
      step1Body:
        "This removes every practice, entry, session and flag, from this phone and from the server. It can't be undone.",
      step1Hint: "You might want to export a copy first.",
      exportFirst: "Export first",
      continue: "Continue",
      keep: "Keep everything",
      step2Label: "Step 2 of 2",
      step2Title: "Last check",
      confirmLabel: "Type DELETE to confirm.",
      confirmWord: "delete",
      confirm: "Delete everything",
      deleting: "Deleting",
      offline: "Deleting needs a connection. Nothing has been deleted.",
      failed: "That didn't go through, so nothing has been deleted. Try again in a minute.",
    },
  },
} as const;
