// Every user-facing string in Daybook. Components import from here; nothing
// user-facing is a literal in a component (CLAUDE.md protocol 5).
// Voice: plain, warm, British. Sentence case. No exclamation marks, no emoji.
// src/copy.test.ts checks every string in this file.

/** "an 8", "a 5": the article for a score read aloud. */
const an = (n: number) => (n === 8 ? "an" : "a");

export const copy = {
  app: {
    name: "Daybook",
    description: "A logbook for the practical side of therapy.",
  },
  // Sign in: boards SignIn and SignInCode. Headings, labels and buttons are
  // the canvas's words; the status lines fill states the canvas doesn't draw.
  signIn: {
    title: "Sign in",
    intro: "We'll email you a 6-digit code. No password to remember.",
    emailLabel: "Email",
    send: "Email me a code",
    sendNeedsEmail: "Enter your email to get a code",
    sending: "Sending a code",
    codeTitle: "Check your email",
    codeIntro: (email: string) => `We sent a code to ${email}. It works for 10 minutes.`,
    codeLabel: "6-digit code",
    verify: "Sign in",
    verifyNeedsCode: "Enter the 6-digit code",
    verifying: "Signing in",
    resend: "Send a new code",
    resent: "A new code is on its way.",
    differentEmail: "Use a different email",
    wrongCode: "That code didn't work. Check it against the latest email, or send a new one.",
    offline: "Signing in needs a connection. Try again when you're back online.",
    sendFailed: "The code couldn't be sent just now. Wait a minute, then try again.",
    privacy: "Your entries are yours. Nothing is shared unless you choose to.",
  },
  // Install prompt: boards Install (iOS) and InstallAndroid, canvas words.
  install: {
    title: "Put Daybook on your home screen",
    intro:
      "Reminders only work once it's there. It takes about ten seconds, and it opens like any other app.",
    iosStep1Before: "Tap the Share button",
    iosStep1After: "at the bottom of Safari.",
    shareLabel: "Share",
    iosStep2Before: "Scroll down and tap",
    iosStep2Strong: "Add to Home Screen",
    iosStep2After: ".",
    iosStep3Before: "Tap",
    iosStep3Strong: "Add",
    iosStep3After: ", then open Daybook from your home screen and sign in once more.",
    shareHint: "Share is down here",
    androidCardTitle: "What you get",
    androidCardBody:
      "Reminders at the times you choose. Logging works with no signal and syncs later. No browser bars.",
    androidFallbackBefore: "If the button doesn't do anything, tap",
    androidFallbackMenu: "⋮",
    androidFallbackMiddle: "in Chrome, then",
    androidFallbackStrong: "Add to Home screen",
    androidFallbackAfter: ".",
    androidInstall: "Install Daybook",
    notNow: "Not now",
  },
  // New / edit session: boards SessionEdit and SessionEditPast (10b), plus
  // the states the canvas doesn't draw (loading offline, saving, not found).
  sessionEdit: {
    newTitle: "New session",
    editTitle: "Edit session",
    close: "Close without saving",
    when: "When",
    hintDefault: (weekday: string) =>
      `Set to the next ${weekday} at your last session's time. Change it if yours is different.`,
    hintFirst: "Pick the date and time of your next appointment.",
    notesLabel: "Session notes",
    notesPlaceholder: "Anything worth keeping from the session",
    assignedHeading: "Assigned in session",
    addPractice: "Add a practice",
    linkFailed:
      "The session's saved, but linking practices didn't go through. Try again from Edit.",
    assignedNoteLabel: "Anything else, not a practice yet",
    assignedNotePlaceholder: "e.g. notice when I check my phone to avoid talking",
    save: "Save session",
    saveNeedsWhen: "Pick a date and time to save",
    saving: "Saving",
    offline: "Saving needs a connection. Your changes are still here.",
    failed: "That didn't save. Your changes are still here, so try again in a minute.",
    loadOffline: "Opening this session needs a connection.",
    notFound: "That session isn't here any more.",
    backToSessions: "Back to sessions",
  },
  // Session detail: boards SessionDetail and SessionDetailPast (0b parts).
  sessionDetail: {
    back: "Sessions",
    edit: "Edit",
    today: "Today",
    upcoming: "Upcoming",
    done: "Done",
    notMarkedDone: "Not marked done",
    notes: "Session notes",
    noNotes: "No notes yet. Add them with Edit.",
    assigned: "Assigned in session",
    practiceType: {
      hierarchy: "Activity hierarchy",
      feelings: "Feelings check-in",
      gratitude: "Gratitude",
    },
    linkPractice: "Link a practice",
    linkTitle: "Link a practice",
    linkNone: "Every practice is already linked to this session.",
    linkOffline: "Linking needs a connection. Nothing has changed.",
    markDone: "Mark session as done",
    marking: "Marking it done",
    markNote: "The entries stay in your history.",
    markOffline: "Marking it done needs a connection. Nothing has changed.",
    markFailed: "That didn't go through, so nothing has changed. Try again in a minute.",
  },
  // App update note (no board; DESIGN.md §5 Note). Never reloads by itself.
  update: {
    ready: "A new version of Daybook is ready.",
    now: "Update now",
  },
  sheet: {
    close: "Close",
  },
  // Ladder: boards Ladder, LadderEmpty, LadderDone (canvas words).
  ladder: {
    back: "Practices",
    rule: "Repeat each task until remaining difficulty is under 4, then move up to the next one.",
    order: "Order",
    easiest: "Easiest first",
    hardest: "Hardest first",
    legendRemaining: "Latest remaining",
    legendRep: "Rep",
    legendAttempt: "Started, left early",
    upNext: "Up next",
    doneBand: "Under 4 · done",
    doneBandLabel: "Under 4 is done",
    doneSection: "Done",
    emptyTitle: "No tasks yet. Add the first rung.",
    emptyBody:
      "Put in everything from your worksheet, in any order. They'll sort themselves, easiest first.",
    add: "Add a task",
    addFirst: "Add the first task",
    week: (n: number, of: number) => `${n} of ${of} this week`,
    oneOff: "One-off",
    oneOffBy: (when: string) => `One-off · by ${when}`,
    today: "today",
    celebrationHeading: "That one's done.",
    celebrationLine: (name: string, remaining: number) =>
      `${name}. Remaining ${remaining}, under the 4 line.`,
    predictionCheck: "Prediction check",
    predictionCheckHint: "Ask what I think will happen before each rep",
    predictionOffline: "Changing this needs a connection. Nothing has changed.",
    notFound: "That practice isn't here any more.",
    loadOffline:
      "This ladder needs a connection the first time. After that it opens on this phone.",
    backToPractices: "Back to practices",
  },
  // Canvas-only controls (DESIGN.md §5) used by the hierarchy screens.
  controls: {
    fewer: "Fewer",
    more: "More",
    minus: "−",
    plus: "+",
    fromTo: (from: number, to: number) => `${from} → ${to}`,
    arrow: "→",
    quote: (text: string) => `“${text}”`,
    on: "On",
    off: "Off",
    other: "Other",
    tallyLabel: (reps: number, attempts: number) =>
      `${reps} ${reps === 1 ? "rep" : "reps"}` +
      (attempts ? `, ${attempts} ${attempts === 1 ? "attempt" : "attempts"}` : ""),
    chartTitle: "Predicted, actual and remaining, rep by rep",
    chartPredicted: "Predicted",
    chartActual: "Actual",
    chartRemaining: "Remaining",
    chartUnderFour: "under 4 is done",
  },
  // The prediction check (plan 0c D1, D15, D16): only with it switched on.
  prediction: {
    beforeHeading: "Before the next one",
    optional: "optional",
    whatWillHappen: "What do you think will happen?",
    howLikely: "How likely does that feel?",
    likelihood: { not_very: "Not very", fairly: "Fairly", very: "Very" },
    beforeHelper: "You'll see this again when you log the rep, and can say whether it happened.",
    afterLead: "Before, you thought",
    didItHappen: "Did it happen?",
    outcome: { no: "No", a_bit: "A bit", yes: "Yes" },
  },
  // Add a task / Edit task: boards AddTask and AddTaskWarning; editing and
  // archiving follow plan 0c D12 (no board).
  addTask: {
    newTitle: "Add a task",
    editTitle: "Edit task",
    close: "Close",
    name: "Task",
    predicted: "Predicted difficulty",
    landsTitle: "Where it lands · easiest first",
    landsLabel: "Where it lands",
    newTag: "New",
    unnamed: "This task",
    highRung: (low: number, high: number) =>
      `This one's high up, and nothing at ${low} or ${high} is done yet. You might want a step in between first. Up to you, you can still add it.`,
    howOften: "How often",
    oneOff: "One-off",
    repeating: "Repeating",
    repsPerWeek: "Reps per week",
    repsHint: "Your worksheet suggests 4 or 5",
    targetDate: "Target date",
    noTarget: "No target date",
    notes: "Notes",
    add: "Add to the ladder",
    save: "Save changes",
    needs: "Name the task and pick a predicted difficulty",
    adding: "Adding it",
    saving: "Saving",
    offline: "Adding or changing a task needs a connection. Everything you typed is still here.",
    failed: "That didn't go through. Everything you typed is still here, so try again in a minute.",
    archive: "Archive this task",
    archiveTitle: "Archive this task?",
    archiveBody: "It leaves the ladder. Its reps stay in your history.",
    archiveConfirm: "Archive it",
    archiveKeep: "Keep it",
    archiveOffline: "Archiving needs a connection. Nothing has changed.",
    notFound: "That task isn't here any more.",
  },
  // Task detail: boards TaskDetail, TaskDetailDone, TaskDetailNew.
  taskDetail: {
    edit: "Edit",
    doneLine: (remaining: number) => `Done. Remaining ${remaining}, under the 4 line.`,
    predicted: "Predicted",
    remaining: "Remaining",
    tally: "Tally",
    noScore: "–",
    repeating: (perWeek: number) => `Repeating, ${perWeek} a week`,
    week: (n: number, of: number) => `${n} of ${of} this week`,
    oneOff: "One-off",
    repCount: (n: number) => `${n} ${n === 1 ? "rep" : "reps"}`,
    by: (when: string) => `by ${when}`,
    metaJoin: " · ",
    // The chart's sentence and alt text (plan 0c D21). "an 8", "a 5".
    storyOne: (predicted: number, actual: number, remaining: number) =>
      `Thought ${predicted}. It was ${an(actual)} ${actual}, and remaining is ${remaining}.`,
    storyMany: (predicted: number, first: number, latest: number, from: number, to: number) =>
      `Thought ${predicted}. The first one was ${an(first)} ${first}, the latest ${an(latest)} ${latest}. Remaining has gone from ${from} to ${to}.`,
    comments: "Comments",
    dateCompleted: (date: string) => `Date completed ${date}`,
    saveComments: "Save comments",
    reps: "Reps",
    repTitle: (n: number) => `Rep ${n}`,
    noReps: "No reps yet.",
    noRepsBody: (predicted: number) =>
      `When you log the first one, it'll show here against the ${predicted} you predicted.`,
    logIt: "Log it",
    logRep: "Log a rep",
    logAnother: "Log another rep",
    notFound: "That task isn't here any more.",
  },
  // Log a rep: boards LogRep, LogRepAttempt, LogRepLogged, LogRepOffline.
  logRep: {
    close: "Close",
    heading: "Log a rep",
    subline: (predicted: number, repNumber: number) =>
      `Predicted difficulty ${predicted} · rep ${repNumber}`,
    sublineWeek: (predicted: number, repNumber: number, week: string) =>
      `Predicted difficulty ${predicted} · rep ${repNumber} · ${week}`,
    howDidItGo: "How did it go?",
    didIt: "Did it",
    leftEarly: "Started, left early",
    openFields: "Note, or anything that made it easier",
    easier: "Anything you did to make it easier?",
    otherLabel: "What was it?",
    addPick: "Add it",
    note: "Note",
    actual: "Actual difficulty",
    actualHint: "How hard was it?",
    remaining: "Remaining difficulty",
    remainingHint: "If you did it again now",
    scoreHint: (n: number) => `${n} of 8`,
    low: "0 easy · under 4 is done",
    high: "8 intense",
    save: "Save rep",
    needsScores: "Pick both scores to save",
    loggedLeftEarly: "Logged as started, left early. It still goes in the tally.",
    loggedDone: (remaining: number) => `That one's done. Remaining ${remaining}, under the 4 line.`,
    logged: (predicted: number, actual: number, remaining: number) =>
      `Logged. Thought ${predicted}, it was ${actual}, now it's ${an(remaining)} ${remaining}.`,
    youThought: (text: string) => `You thought: “${text}”`,
    outcomeLine: {
      no: "It didn't happen.",
      a_bit: "A bit of it happened, and you stayed with it.",
      yes: "It happened, and you did it anyway.",
    },
    predicted: "Predicted",
    actualShort: "Actual",
    remainingShort: "Remaining",
    tally: "Tally",
    thisWeek: "This week",
    weekAfter: (n: number, of: number, leftEarly: number) =>
      leftEarly ? `${n} of ${of}, ${leftEarly} left early` : `${n} of ${of}`,
    bringToSession: "Bring to session",
    flagged: "Flagged",
    notFlagged: "Off",
    changeSomething: "Change something",
    done: "Done",
    notFound: "That task isn't here any more.",
  },
  // Shared field words (DateTimeField, TextArea).
  fields: {
    date: "Date",
    time: "Time",
    pickDate: "Pick a date",
    pickTime: "Pick a time",
    dateChange: (value: string) => `Date, ${value}. Change`,
    timeChange: (value: string) => `Time, ${value}. Change`,
    optional: "(optional)",
    change: "Change",
  },
  // Placeholder screens for the tabs whose content arrives in later phases.
  // Each is replaced when its phase builds the real screen.
  today: {
    title: "Today",
    emptyTitle: "Nothing to log yet",
    emptyBody: "Once a practice is set up, what's on for today shows here.",
  },
  // Practices: boards Practices, PracticesEmpty, PracticesPicker. The boards'
  // therapist wording is replaced so practices never depend on a session
  // (plan 0c D9); everything else is the canvas's words.
  practices: {
    title: "Practices",
    active: (n: number) => `${n} active`,
    emptyTitle: "No practices yet",
    emptyBody:
      "Each worksheet becomes a practice, whether it came from a session or not. Add the first one.",
    add: "Add a practice",
    addFirst: "Add the first practice",
    meta: (onTheGo: number, done: number) =>
      onTheGo + done === 0
        ? "No tasks yet"
        : `${onTheGo} ${onTheGo === 1 ? "task" : "tasks"} on the go, ${done} done`,
    sheetTitle: "Add a practice",
    sheetLead: "Which worksheet is it?",
    hierarchyName: "Activity hierarchy",
    hierarchyLine: "A ladder of tasks, easiest first. Log reps and scores.",
    alreadyAdded: "Already on your list. Tap to open it.",
    sheetFooter: "Each worksheet gets its own screen, so new types get added one at a time.",
    adding: "Adding it",
    addOffline: "Adding a practice needs a connection. Try again when you're back online.",
    addFailed: "That didn't go through. Try again in a minute.",
    loadOffline: "Practices need a connection the first time. After that they open on this phone.",
  },
  // Sessions list: boards Sessions and SessionsEmpty (canvas words), plus the
  // states the canvas doesn't draw (later sessions, loading offline).
  sessions: {
    title: "Sessions",
    emptyTitle: "No sessions yet",
    emptyBody: "Add your next appointment. Anything you flag will collect for it.",
    addFirst: "Add your next session",
    add: "Add a session",
    next: "Next session",
    today: "Today",
    tomorrow: "Tomorrow",
    days: "days",
    nextLabel: (date: string, time: string, when: string) =>
      `Next session, ${date} at ${time}, ${when}`,
    inDays: (n: number) => `in ${n} days`,
    later: "Later",
    past: "Past",
    noNotes: "No notes",
    markedDone: "Marked done",
    notMarkedDone: "Not marked done",
    rowMeta: (time: string, status: string) => `${time} · ${status}`,
    offline:
      "Sessions need a connection to load. Anything you add on the edit screen needs one too.",
    failed: "Sessions didn't load just now. Try again in a minute.",
  },
  history: {
    title: "History",
    emptyTitle: "Nothing logged yet",
    emptyBody: "Everything you log is kept here, newest first.",
  },
  // Settings: boards Settings, SettingsDelete1, SettingsDelete2. Canvas words,
  // plus the states it doesn't draw (busy, offline, not installed).
  settings: {
    title: "Settings",
    installRow: "Add to home screen",
    installed: "Installed on this phone",
    notInstalled: "Not on this phone yet",
    dataHeading: "Your data",
    exportRow: "Export my data",
    exportMeta: "Everything, as a JSON file. PDF comes later.",
    exporting: "Getting everything together",
    exportDone: "Exported. Check your downloads or Files.",
    exportOffline: "Exporting needs a connection. Try again when you're back online.",
    exportFailed: "The export didn't come through. Try again in a minute.",
    deleteRow: "Delete everything",
    deleteMeta: "From this phone and the server. Two steps.",
    about: "About Daybook",
    version: (v: string) => `Version ${v}`,
    signOut: "Sign out",
    footer: "Daybook is a logbook, not a coach and not emergency support.",
    delete: {
      step1Label: "Step 1 of 2",
      step1Title: "Delete everything?",
      step1Body:
        "This removes every practice, entry, session and flag, from this phone and from the server. It can't be undone.",
      step1Hint: "You might want to export a copy first.",
      exportFirst: "Export first",
      continue: "Continue",
      keep: "Keep everything",
      step2Label: "Step 2 of 2",
      step2Title: "Last check",
      confirmLabel: "Type DELETE to confirm.",
      confirmWord: "delete",
      confirm: "Delete everything",
      deleting: "Deleting",
      offline: "Deleting needs a connection. Nothing has been deleted.",
      failed: "That didn't go through, so nothing has been deleted. Try again in a minute.",
    },
  },
} as const;
